package quizzically.lib;

import java.sql.*;

import quizzically.config.MyDBInfo;

/**
 * Establishes a connection to a MySQL database using MySQL JDBC Driver.
 */
public class DBConnection {
	
	private Connection con;
	
	public DBConnection() throws ClassNotFoundException, SQLException {
		Class.forName("com.mysql.jdbc.Driver");
		 
		con = DriverManager.getConnection("jdbc:mysql://" + MyDBInfo.MYSQL_DATABASE_SERVER,
				 											MyDBInfo.MYSQL_USERNAME,
				 											MyDBInfo.MYSQL_PASSWORD);
	}
	
	/**
	 * Creates a database connection, executes a SQL query to select a specific database,
	 * and returns a prepared SQL statement object. It throws a SQLException if an error
	 * occurs. The selected database is specified by the `MYSQL_DATABASE_NAME` constant.
	 *
	 * @returns a Statement object.
	 */
	public Statement getStatement() throws SQLException {
		Statement stmt = con.createStatement();
		stmt.executeQuery("USE " + MyDBInfo.MYSQL_DATABASE_NAME);
		return stmt;
	}
	
	/**
	 * Prepares a SQL statement for execution and sets the database context by executing
	 * a USE statement. It returns a prepared statement object. The USE statement selects
	 * the database specified in the MyDBInfo constant.
	 *
	 * @param sql query to be executed by the prepared statement, which in this case is
	 * not used as intended.
	 *
	 * @returns a PreparedStatement object used to execute SQL queries on a MySQL database.
	 */
	public PreparedStatement prepareStatement(String sql) throws SQLException {
		PreparedStatement stmt = con.prepareStatement(sql);
		stmt.executeQuery("USE " + MyDBInfo.MYSQL_DATABASE_NAME);
		return stmt;
	}
	
	/**
	 * Prepares a SQL statement for execution and returns a `PreparedStatement` object.
	 * The statement is created with the specified SQL query and auto-generated keys option.
	 *
	 * @param sql SQL query to be executed by the `prepareStatement` method.
	 *
	 * @param autoGeneratedKeys type of auto-generated keys to retrieve after executing
	 * the SQL statement.
	 *
	 * @returns a `PreparedStatement` object, allowing for SQL execution with auto-generated
	 * keys.
	 */
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		PreparedStatement stmt = con.prepareStatement(sql, autoGeneratedKeys);
//		stmt.executeQuery("USE " + MyDBInfo.MYSQL_DATABASE_NAME);
		return stmt;
	}
	
	/**
	 * Closes a database connection, attempting to release resources.
	 */
	public void close() {
		try {
			con.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
}
